redirectsOrigin = "config"
plugins = []
headers = []

[functions]

  [functions."*"]

[build]

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[redirects]]
from = "/implementation.html"
to = "/implementation"
status = 301
force = true

[[redirects]]
from = "/architect.html"
to = "/architect"
status = 301
force = true

[[redirects]]
from = "/evidence.html"
to = "/evidence"
status = 301
force = true

[[redirects]]
from = "/trades.html"
to = "/trades"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/rogueos.html"
to = "/rogueos"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/glossary.html"
to = "/glossary"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/framework.html"
to = "/framework"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/about.html"
to = "/architect"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]